FROM covex/php7.1-fpm:master

ENV APP_ENV=dev
ENV APP_DEBUG=1

RUN docker-php-ext-enable xdebug \
    && adduser --system --no-create-home --uid 1000 --gid 50 docker \
    && mkdir -p /tmp/sessions \
    && chmod -R 777 /tmp/sessions

WORKDIR /srv
