FROM covex/php7.1-fpm:latest

ENV APP_ENV=dev
ENV APP_DEBUG=1

RUN docker-php-ext-enable xdebug \
    && addgroup -g 50 docker \
    && adduser -D -u 1000 -G docker docker \
    && mkdir -p /tmp/sessions \
    && chmod -R 777 /tmp/sessions

WORKDIR /srv
