ARG app_image=scratch
FROM nginx:mainline AS base

ARG server_name=docker.local
ARG server_upstream=dev

COPY docker/nginx/default.conf /etc/nginx/conf.d/
COPY docker/nginx/backend_${server_upstream}.conf /etc/nginx/conf.d/backend.conf

RUN sed -i 's/@SERVER_NAME@/'"$server_name"'/g' /etc/nginx/conf.d/default.conf



FROM ${app_image} AS app
FROM base AS prod

COPY --from=app /srv/public/ /srv/public/
